#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focused_border_color "#29A8E0" # Cyan-Blue for active window
bspc config normal_border_color "#505050"  # Gray for inactive windows
bspc config active_border_color "#C0C0C0"  # Light gray for attention
bspc config presel_border_color "#E94E77"  # Pink-Red for preselection

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
feh --bg-fill ~/Pictures/backgrounds/bg0.png
bspc config focus_follows_pointer true
~/.config/polybar/./launch.sh
picom --experimental-backends &
bspc config border_width 0
wmname LG3D &
#setxkbmap -option grp:alt_shift_toggle us,latam &
